// All 114 surahs of the Quran with English transliteration, Arabic name,
// Bangla name, ayah count, and place of revelation.
// Source: well-known canonical metadata; ayah counts follow the Hafs an Asim recension
// (the standard recension used in Bangladesh).

export type Revelation = "Meccan" | "Medinan";

export interface Surah {
  number: number;
  name: string;        // English transliteration (e.g. "Al-Fatihah")
  arabicName: string;  // Arabic script (e.g. "الفاتحة")
  banglaName: string;  // Bangla transliteration (e.g. "আল-ফাতিহা")
  ayahs: number;
  revelation: Revelation;
}

export const SURAHS: Surah[] = [
  { number: 1, name: "Al-Fatihah", arabicName: "الفاتحة", banglaName: "আল-ফাতিহা", ayahs: 7, revelation: "Meccan" },
  { number: 2, name: "Al-Baqarah", arabicName: "البقرة", banglaName: "আল-বাকারাহ", ayahs: 286, revelation: "Medinan" },
  { number: 3, name: "Aal-E-Imran", arabicName: "آل عمران", banglaName: "আলে ইমরান", ayahs: 200, revelation: "Medinan" },
  { number: 4, name: "An-Nisa", arabicName: "النساء", banglaName: "আন-নিসা", ayahs: 176, revelation: "Medinan" },
  { number: 5, name: "Al-Ma'idah", arabicName: "المائدة", banglaName: "আল-মায়িদাহ", ayahs: 120, revelation: "Medinan" },
  { number: 6, name: "Al-An'am", arabicName: "الأنعام", banglaName: "আল-আনআম", ayahs: 165, revelation: "Meccan" },
  { number: 7, name: "Al-A'raf", arabicName: "الأعراف", banglaName: "আল-আরাফ", ayahs: 206, revelation: "Meccan" },
  { number: 8, name: "Al-Anfal", arabicName: "الأنفال", banglaName: "আল-আনফাল", ayahs: 75, revelation: "Medinan" },
  { number: 9, name: "At-Tawbah", arabicName: "التوبة", banglaName: "আত-তাওবা", ayahs: 129, revelation: "Medinan" },
  { number: 10, name: "Yunus", arabicName: "يونس", banglaName: "ইউনুস", ayahs: 109, revelation: "Meccan" },
  { number: 11, name: "Hud", arabicName: "هود", banglaName: "হুদ", ayahs: 123, revelation: "Meccan" },
  { number: 12, name: "Yusuf", arabicName: "يوسف", banglaName: "ইউসুফ", ayahs: 111, revelation: "Meccan" },
  { number: 13, name: "Ar-Ra'd", arabicName: "الرعد", banglaName: "আর-রাদ", ayahs: 43, revelation: "Medinan" },
  { number: 14, name: "Ibrahim", arabicName: "إبراهيم", banglaName: "ইব্রাহিম", ayahs: 52, revelation: "Meccan" },
  { number: 15, name: "Al-Hijr", arabicName: "الحجر", banglaName: "আল-হিজর", ayahs: 99, revelation: "Meccan" },
  { number: 16, name: "An-Nahl", arabicName: "النحل", banglaName: "আন-নাহল", ayahs: 128, revelation: "Meccan" },
  { number: 17, name: "Al-Isra", arabicName: "الإسراء", banglaName: "আল-ইসরা", ayahs: 111, revelation: "Meccan" },
  { number: 18, name: "Al-Kahf", arabicName: "الكهف", banglaName: "আল-কাহফ", ayahs: 110, revelation: "Meccan" },
  { number: 19, name: "Maryam", arabicName: "مريم", banglaName: "মারইয়াম", ayahs: 98, revelation: "Meccan" },
  { number: 20, name: "Ta-Ha", arabicName: "طه", banglaName: "ত্বহা", ayahs: 135, revelation: "Meccan" },
  { number: 21, name: "Al-Anbiya", arabicName: "الأنبياء", banglaName: "আল-আম্বিয়া", ayahs: 112, revelation: "Meccan" },
  { number: 22, name: "Al-Hajj", arabicName: "الحج", banglaName: "আল-হাজ্জ", ayahs: 78, revelation: "Medinan" },
  { number: 23, name: "Al-Mu'minun", arabicName: "المؤمنون", banglaName: "আল-মুমিনুন", ayahs: 118, revelation: "Meccan" },
  { number: 24, name: "An-Nur", arabicName: "النور", banglaName: "আন-নূর", ayahs: 64, revelation: "Medinan" },
  { number: 25, name: "Al-Furqan", arabicName: "الفرقان", banglaName: "আল-ফুরকান", ayahs: 77, revelation: "Meccan" },
  { number: 26, name: "Ash-Shu'ara", arabicName: "الشعراء", banglaName: "আশ-শুআরা", ayahs: 227, revelation: "Meccan" },
  { number: 27, name: "An-Naml", arabicName: "النمل", banglaName: "আন-নামল", ayahs: 93, revelation: "Meccan" },
  { number: 28, name: "Al-Qasas", arabicName: "القصص", banglaName: "আল-কাসাস", ayahs: 88, revelation: "Meccan" },
  { number: 29, name: "Al-Ankabut", arabicName: "العنكبوت", banglaName: "আল-আনকাবূত", ayahs: 69, revelation: "Meccan" },
  { number: 30, name: "Ar-Rum", arabicName: "الروم", banglaName: "আর-রূম", ayahs: 60, revelation: "Meccan" },
  { number: 31, name: "Luqman", arabicName: "لقمان", banglaName: "লুকমান", ayahs: 34, revelation: "Meccan" },
  { number: 32, name: "As-Sajdah", arabicName: "السجدة", banglaName: "আস-সাজদাহ", ayahs: 30, revelation: "Meccan" },
  { number: 33, name: "Al-Ahzab", arabicName: "الأحزاب", banglaName: "আল-আহযাব", ayahs: 73, revelation: "Medinan" },
  { number: 34, name: "Saba", arabicName: "سبأ", banglaName: "সাবা", ayahs: 54, revelation: "Meccan" },
  { number: 35, name: "Fatir", arabicName: "فاطر", banglaName: "ফাতির", ayahs: 45, revelation: "Meccan" },
  { number: 36, name: "Ya-Sin", arabicName: "يس", banglaName: "ইয়াসীন", ayahs: 83, revelation: "Meccan" },
  { number: 37, name: "As-Saffat", arabicName: "الصافات", banglaName: "আস-সাফফাত", ayahs: 182, revelation: "Meccan" },
  { number: 38, name: "Sad", arabicName: "ص", banglaName: "সাদ", ayahs: 88, revelation: "Meccan" },
  { number: 39, name: "Az-Zumar", arabicName: "الزمر", banglaName: "আয-যুমার", ayahs: 75, revelation: "Meccan" },
  { number: 40, name: "Ghafir", arabicName: "غافر", banglaName: "গাফির", ayahs: 85, revelation: "Meccan" },
  { number: 41, name: "Fussilat", arabicName: "فصلت", banglaName: "ফুসসিলাত", ayahs: 54, revelation: "Meccan" },
  { number: 42, name: "Ash-Shura", arabicName: "الشورى", banglaName: "আশ-শুরা", ayahs: 53, revelation: "Meccan" },
  { number: 43, name: "Az-Zukhruf", arabicName: "الزخرف", banglaName: "আয-যুখরুফ", ayahs: 89, revelation: "Meccan" },
  { number: 44, name: "Ad-Dukhan", arabicName: "الدخان", banglaName: "আদ-দুখান", ayahs: 59, revelation: "Meccan" },
  { number: 45, name: "Al-Jathiyah", arabicName: "الجاثية", banglaName: "আল-জাসিয়া", ayahs: 37, revelation: "Meccan" },
  { number: 46, name: "Al-Ahqaf", arabicName: "الأحقاف", banglaName: "আল-আহকাফ", ayahs: 35, revelation: "Meccan" },
  { number: 47, name: "Muhammad", arabicName: "محمد", banglaName: "মুহাম্মাদ", ayahs: 38, revelation: "Medinan" },
  { number: 48, name: "Al-Fath", arabicName: "الفتح", banglaName: "আল-ফাতহ", ayahs: 29, revelation: "Medinan" },
  { number: 49, name: "Al-Hujurat", arabicName: "الحجرات", banglaName: "আল-হুজুরাত", ayahs: 18, revelation: "Medinan" },
  { number: 50, name: "Qaf", arabicName: "ق", banglaName: "কাফ", ayahs: 45, revelation: "Meccan" },
  { number: 51, name: "Adh-Dhariyat", arabicName: "الذاريات", banglaName: "আয-যারিয়াত", ayahs: 60, revelation: "Meccan" },
  { number: 52, name: "At-Tur", arabicName: "الطور", banglaName: "আত-তূর", ayahs: 49, revelation: "Meccan" },
  { number: 53, name: "An-Najm", arabicName: "النجم", banglaName: "আন-নাজম", ayahs: 62, revelation: "Meccan" },
  { number: 54, name: "Al-Qamar", arabicName: "القمر", banglaName: "আল-কামার", ayahs: 55, revelation: "Meccan" },
  { number: 55, name: "Ar-Rahman", arabicName: "الرحمن", banglaName: "আর-রাহমান", ayahs: 78, revelation: "Medinan" },
  { number: 56, name: "Al-Waqi'ah", arabicName: "الواقعة", banglaName: "আল-ওয়াকিআহ", ayahs: 96, revelation: "Meccan" },
  { number: 57, name: "Al-Hadid", arabicName: "الحديد", banglaName: "আল-হাদীদ", ayahs: 29, revelation: "Medinan" },
  { number: 58, name: "Al-Mujadilah", arabicName: "المجادلة", banglaName: "আল-মুজাদালাহ", ayahs: 22, revelation: "Medinan" },
  { number: 59, name: "Al-Hashr", arabicName: "الحشر", banglaName: "আল-হাশর", ayahs: 24, revelation: "Medinan" },
  { number: 60, name: "Al-Mumtahanah", arabicName: "الممتحنة", banglaName: "আল-মুমতাহিনাহ", ayahs: 13, revelation: "Medinan" },
  { number: 61, name: "As-Saff", arabicName: "الصف", banglaName: "আস-সাফ", ayahs: 14, revelation: "Medinan" },
  { number: 62, name: "Al-Jumu'ah", arabicName: "الجمعة", banglaName: "আল-জুমুআ", ayahs: 11, revelation: "Medinan" },
  { number: 63, name: "Al-Munafiqun", arabicName: "المنافقون", banglaName: "আল-মুনাফিকূন", ayahs: 11, revelation: "Medinan" },
  { number: 64, name: "At-Taghabun", arabicName: "التغابن", banglaName: "আত-তাগাবুন", ayahs: 18, revelation: "Medinan" },
  { number: 65, name: "At-Talaq", arabicName: "الطلاق", banglaName: "আত-তালাক", ayahs: 12, revelation: "Medinan" },
  { number: 66, name: "At-Tahrim", arabicName: "التحريم", banglaName: "আত-তাহরীম", ayahs: 12, revelation: "Medinan" },
  { number: 67, name: "Al-Mulk", arabicName: "الملك", banglaName: "আল-মুলক", ayahs: 30, revelation: "Meccan" },
  { number: 68, name: "Al-Qalam", arabicName: "القلم", banglaName: "আল-কলম", ayahs: 52, revelation: "Meccan" },
  { number: 69, name: "Al-Haqqah", arabicName: "الحاقة", banglaName: "আল-হাক্কাহ", ayahs: 52, revelation: "Meccan" },
  { number: 70, name: "Al-Ma'arij", arabicName: "المعارج", banglaName: "আল-মাআরিজ", ayahs: 44, revelation: "Meccan" },
  { number: 71, name: "Nuh", arabicName: "نوح", banglaName: "নূহ", ayahs: 28, revelation: "Meccan" },
  { number: 72, name: "Al-Jinn", arabicName: "الجن", banglaName: "আল-জিন", ayahs: 28, revelation: "Meccan" },
  { number: 73, name: "Al-Muzzammil", arabicName: "المزمل", banglaName: "আল-মুযযামমিল", ayahs: 20, revelation: "Meccan" },
  { number: 74, name: "Al-Muddaththir", arabicName: "المدثر", banglaName: "আল-মুদ্দাসসির", ayahs: 56, revelation: "Meccan" },
  { number: 75, name: "Al-Qiyamah", arabicName: "القيامة", banglaName: "আল-কিয়ামাহ", ayahs: 40, revelation: "Meccan" },
  { number: 76, name: "Al-Insan", arabicName: "الإنسان", banglaName: "আল-ইনসান", ayahs: 31, revelation: "Medinan" },
  { number: 77, name: "Al-Mursalat", arabicName: "المرسلات", banglaName: "আল-মুরসালাত", ayahs: 50, revelation: "Meccan" },
  { number: 78, name: "An-Naba", arabicName: "النبأ", banglaName: "আন-নাবা", ayahs: 40, revelation: "Meccan" },
  { number: 79, name: "An-Nazi'at", arabicName: "النازعات", banglaName: "আন-নাযিআত", ayahs: 46, revelation: "Meccan" },
  { number: 80, name: "Abasa", arabicName: "عبس", banglaName: "আবাসা", ayahs: 42, revelation: "Meccan" },
  { number: 81, name: "At-Takwir", arabicName: "التكوير", banglaName: "আত-তাকভীর", ayahs: 29, revelation: "Meccan" },
  { number: 82, name: "Al-Infitar", arabicName: "الانفطار", banglaName: "আল-ইনফিতার", ayahs: 19, revelation: "Meccan" },
  { number: 83, name: "Al-Mutaffifin", arabicName: "المطففين", banglaName: "আল-মুতাফফিফীন", ayahs: 36, revelation: "Meccan" },
  { number: 84, name: "Al-Inshiqaq", arabicName: "الانشقاق", banglaName: "আল-ইনশিকাক", ayahs: 25, revelation: "Meccan" },
  { number: 85, name: "Al-Buruj", arabicName: "البروج", banglaName: "আল-বুরূজ", ayahs: 22, revelation: "Meccan" },
  { number: 86, name: "At-Tariq", arabicName: "الطارق", banglaName: "আত-তারিক", ayahs: 17, revelation: "Meccan" },
  { number: 87, name: "Al-A'la", arabicName: "الأعلى", banglaName: "আল-আলা", ayahs: 19, revelation: "Meccan" },
  { number: 88, name: "Al-Ghashiyah", arabicName: "الغاشية", banglaName: "আল-গাশিয়াহ", ayahs: 26, revelation: "Meccan" },
  { number: 89, name: "Al-Fajr", arabicName: "الفجر", banglaName: "আল-ফাজর", ayahs: 30, revelation: "Meccan" },
  { number: 90, name: "Al-Balad", arabicName: "البلد", banglaName: "আল-বালাদ", ayahs: 20, revelation: "Meccan" },
  { number: 91, name: "Ash-Shams", arabicName: "الشمس", banglaName: "আশ-শামস", ayahs: 15, revelation: "Meccan" },
  { number: 92, name: "Al-Layl", arabicName: "الليل", banglaName: "আল-লাইল", ayahs: 21, revelation: "Meccan" },
  { number: 93, name: "Ad-Duha", arabicName: "الضحى", banglaName: "আদ-দুহা", ayahs: 11, revelation: "Meccan" },
  { number: 94, name: "Ash-Sharh", arabicName: "الشرح", banglaName: "আশ-শারহ", ayahs: 8, revelation: "Meccan" },
  { number: 95, name: "At-Tin", arabicName: "التين", banglaName: "আত-তীন", ayahs: 8, revelation: "Meccan" },
  { number: 96, name: "Al-Alaq", arabicName: "العلق", banglaName: "আল-আলাক", ayahs: 19, revelation: "Meccan" },
  { number: 97, name: "Al-Qadr", arabicName: "القدر", banglaName: "আল-কদর", ayahs: 5, revelation: "Meccan" },
  { number: 98, name: "Al-Bayyinah", arabicName: "البينة", banglaName: "আল-বাইয়িনাহ", ayahs: 8, revelation: "Medinan" },
  { number: 99, name: "Az-Zalzalah", arabicName: "الزلزلة", banglaName: "আয-যিলযাল", ayahs: 8, revelation: "Medinan" },
  { number: 100, name: "Al-Adiyat", arabicName: "العاديات", banglaName: "আল-আদিয়াত", ayahs: 11, revelation: "Meccan" },
  { number: 101, name: "Al-Qari'ah", arabicName: "القارعة", banglaName: "আল-কারিআহ", ayahs: 11, revelation: "Meccan" },
  { number: 102, name: "At-Takathur", arabicName: "التكاثر", banglaName: "আত-তাকাসুর", ayahs: 8, revelation: "Meccan" },
  { number: 103, name: "Al-Asr", arabicName: "العصر", banglaName: "আল-আসর", ayahs: 3, revelation: "Meccan" },
  { number: 104, name: "Al-Humazah", arabicName: "الهمزة", banglaName: "আল-হুমাযাহ", ayahs: 9, revelation: "Meccan" },
  { number: 105, name: "Al-Fil", arabicName: "الفيل", banglaName: "আল-ফীল", ayahs: 5, revelation: "Meccan" },
  { number: 106, name: "Quraysh", arabicName: "قريش", banglaName: "কুরাইশ", ayahs: 4, revelation: "Meccan" },
  { number: 107, name: "Al-Ma'un", arabicName: "الماعون", banglaName: "আল-মাঊন", ayahs: 7, revelation: "Meccan" },
  { number: 108, name: "Al-Kawthar", arabicName: "الكوثر", banglaName: "আল-কাওসার", ayahs: 3, revelation: "Meccan" },
  { number: 109, name: "Al-Kafirun", arabicName: "الكافرون", banglaName: "আল-কাফিরূন", ayahs: 6, revelation: "Meccan" },
  { number: 110, name: "An-Nasr", arabicName: "النصر", banglaName: "আন-নাসর", ayahs: 3, revelation: "Medinan" },
  { number: 111, name: "Al-Masad", arabicName: "المسد", banglaName: "আল-মাসাদ", ayahs: 5, revelation: "Meccan" },
  { number: 112, name: "Al-Ikhlas", arabicName: "الإخلاص", banglaName: "আল-ইখলাস", ayahs: 4, revelation: "Meccan" },
  { number: 113, name: "Al-Falaq", arabicName: "الفلق", banglaName: "আল-ফালাক", ayahs: 5, revelation: "Meccan" },
  { number: 114, name: "An-Nas", arabicName: "الناس", banglaName: "আন-নাস", ayahs: 6, revelation: "Meccan" },
];

export function findSurah(number: number): Surah | undefined {
  return SURAHS.find((s) => s.number === number);
}
